apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-mongodb
spec:
  selector:
    matchLabels:
      app: easytravel-mongodb
  template:
    metadata:
      labels:
        app: easytravel-mongodb
    spec:
      containers:
        - name: easytravel-mongodb
          image: dynatrace/easytravel-mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
            - containerPort: 28017
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-backend
spec:
  selector:
    matchLabels:
      app: easytravel-backend
  template:
    metadata:
      labels:
        app: easytravel-backend
    spec:
      containers:
        - name: easytravel-backend
          image: dynatrace/easytravel-backend
          env:
            - name: ET_DATABASE_LOCATION
              value: easytravel-mongodb:27017
            - name: ET_DATABASE_USER
              value: "etAdmin"
            - name: ET_DATABASE_PASSWORD
              value: "adminadmin"
            - name: ET_MONGO_AUTH_DB
              value: "admin"
          ports:
            - containerPort: 8080
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-frontend
spec:
  selector:
    matchLabels:
      app: easytravel-frontend
  template:
    metadata:
      labels:
        app: easytravel-frontend
    spec:
      containers:
        - name: easytravel-frontend
          image: dynatrace/easytravel-frontend
          env:
            - name: ET_BACKEND_URL
              value: http://easytravel-backend:8080
          ports:
            - containerPort: 8080
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-www
spec:
  selector:
    matchLabels:
      app: easytravel-www
  template:
    metadata:
      labels:
        app: easytravel-www
    spec:
      containers:
        - name: easytravel-nginx
          image: dynatrace/easytravel-nginx
          env:
            - name: ET_FRONTEND_LOCATION
              value: easytravel-frontend:8080
            - name: ET_BACKEND_LOCATION
              value: easytravel-backend:8080
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: easytravel-mongodb
spec:
  ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    - name: 28017-tcp
      port: 28017
      protocol: TCP
      targetPort: 28017
  selector:
    app: easytravel-mongodb
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: easytravel-backend
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: easytravel-backend
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: easytravel-frontend
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: easytravel-frontend
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: easytravel-www
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: easytravel-www
  type: ClusterIP
